import Image1 from "../../assets/Images/CategoriesImages/category_image.png"

export const categoriesData=[
    {
        key:1,
        image:Image1,
        name:"asdf1"
    },
    {
        key:2,
        image:Image1,
        name:"asdf2"
    },
    {
        key:3,
        image:Image1,
        name:"asdf3"
    },
    {
        key:4,
        image:Image1,
        name:"asdf4"
    },
    {
        key:5,
        image:Image1,
        name:"asdf5"
    },
    {
        key:6,
        image:Image1,
        name:"asdf6"
    },
    {
        key:7,
        image:Image1,
        name:"asdf7"
    },
    {
        key:8,
        image:Image1,
        name:"asdf8"
    }
]